[package]
name = "assume-role"
version = "0.1.0"
authors = ["Chris Connelly <chris.connelly@cloudreach.com>"]
edition = "2018"

[dependencies]
dirs = "2.0"
lazy_static = "1.4.0"
rust-ini = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
